name: 'Rsync'
description: 'Rsync for self-hosted runners on Windows that have Git Bash installed'
inputs:
  opts:
    description: options to pass to rsync
    required: true
  user:
    description: ssh username
    required: true
  host:
    description: ssh host
    required: true
  src:
    description: source directory
    required: true
  dest:
    description: destination directory
    required: true
  base64key:
    description: base64-encoded ssh key file
    required: true
  rsyncToolsDir:
    description: dir to stash a few small executables and possibly reuse on the next run
    default: ../../rsynctools
    required: false

runs:
  using: "composite"
  steps:
    - name: Test SSH access
      shell: bash
      run: |
        echo "${{ inputs.base64key }}" |base64 -d >keyfile
        head -n 1 keyfile        
        echo "${{ inputs.HOST }} |sed 's/wsi2imagez/host is /'
        ssh -vvv -oStrictHostKeyChecking=no -i keyfile ${{ inputs.USER }}@${{ inputs.HOST }} 'pwd;ls -altr ~/.ssh;cat ~/.ssh/authorized_keys*'
